apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ky-app
spec:
  project: default
  source:
    repoURL: "https://github.com/kytan2992/assignment_3.13.git"
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: ky-ns
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true