apiVersion: apps/v1
kind: Deployment
metadata:
  name: ky-echo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
        - name: echo-container
          image: hashicorp/http-echo
          args:
            - "-text=Hello, KE YANG!"
          ports:
            - containerPort: 5678
